name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: centos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to web server
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.SERVER }}
          remote_user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/home/tamao/files/test"
